import "server-only";

import { randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { isValidUserId } from "@/lib/auth/store";
import { storagePath } from "@/lib/storage";
import { MAX_UPLOAD_BYTES, kindForExt, type StoredDoc } from "./types";

/**
 * Filesystem store for uploaded documents, one directory per account:
 *
 *   storage/documents/<ownerId>/<id>.<ext>       the bytes, exactly as uploaded
 *   storage/documents/<ownerId>/<id>.meta.json   the StoredDoc record
 *
 * **Every function takes the owner id and builds its path from it.** That is
 * the isolation: there is no way to name a file outside the caller's own
 * directory, so a forgotten ownership check can't leak another account's
 * documents — the path simply doesn't resolve. `ownerId` is written into each
 * record too, so a file moved between directories by hand is still not served
 * to the wrong account.
 *
 * Sidecars rather than one index file so two concurrent uploads can't clobber
 * each other's entry. The directory is gitignored and lives outside `src/` so
 * nothing here is ever bundled or served statically — every read goes through
 * the API routes, which decide the content type.
 *
 * Deliberately a plain directory, not a database: this phase is local demo
 * work, and swapping in object storage later means reimplementing only the
 * five functions below.
 */

const DOCUMENTS = "documents";

/** Ids are generated by us, so anything else is a path-traversal attempt. */
const VALID_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

const META_SUFFIX = ".meta.json";

export function isValidId(id: string): boolean {
  return VALID_ID.test(id);
}

function ownerDir(ownerId: string): string {
  // Belt and braces: storagePath rejects separators, and the id is checked
  // against the account-id shape before it is ever used as a directory name.
  if (!isValidUserId(ownerId)) throw new Error("Invalid owner id");
  return storagePath(DOCUMENTS, ownerId);
}

async function ensureDir(ownerId: string): Promise<void> {
  await mkdir(/*turbopackIgnore: true*/ ownerDir(ownerId), { recursive: true });
}

/**
 * Extension from the uploaded name: lowercased, stripped to alphanumerics
 * and capped, so it can never contribute a path separator or a dot to the
 * name we write. Falls back to "bin".
 */
function safeExt(filename: string): string {
  const dot = filename.lastIndexOf(".");
  if (dot < 0 || dot === filename.length - 1) return "bin";
  const raw = filename.slice(dot + 1).toLowerCase();
  const cleaned = raw.replace(/[^a-z0-9]/g, "").slice(0, 8);
  return cleaned || "bin";
}

/** Display name only — the name on disk is always `<uuid>.<ext>`. */
function safeName(filename: string): string {
  const base = filename.split(/[/\\]/).pop() ?? filename;
  const cleaned = base.replace(/[\u0000-\u001f\u007f]/g, "").trim();
  return (cleaned || "untitled").slice(0, 200);
}

function blobPath(doc: Pick<StoredDoc, "id" | "ext" | "ownerId">): string {
  return storagePath(DOCUMENTS, doc.ownerId, `${doc.id}.${doc.ext}`);
}

function metaPath(ownerId: string, id: string): string {
  return storagePath(DOCUMENTS, ownerId, `${id}${META_SUFFIX}`);
}

/* ------------------------------------------------------------------ */

/** Everything this account has uploaded, newest first. */
export async function listDocs(ownerId: string): Promise<StoredDoc[]> {
  await ensureDir(ownerId);
  const entries = await readdir(/*turbopackIgnore: true*/ ownerDir(ownerId));
  const docs: StoredDoc[] = [];

  for (const entry of entries) {
    if (!entry.endsWith(META_SUFFIX)) continue;
    // Read through getDoc so there is one sidecar-reading path, and so a
    // stray file whose name isn't a uuid is skipped rather than parsed.
    // A half-written sidecar returns null and doesn't take the list down.
    const doc = await getDoc(ownerId, entry.slice(0, -META_SUFFIX.length));
    if (doc) docs.push(doc);
  }

  return docs.sort((a, b) => b.uploadedAt.localeCompare(a.uploadedAt));
}

/** One document, but only if it belongs to this account. */
export async function getDoc(ownerId: string, id: string): Promise<StoredDoc | null> {
  if (!isValidId(id) || !isValidUserId(ownerId)) return null;

  let doc: StoredDoc;
  try {
    doc = JSON.parse(await readFile(/*turbopackIgnore: true*/ metaPath(ownerId, id), "utf-8"));
  } catch {
    return null;
  }

  return doc.ownerId === ownerId ? doc : null;
}

export async function readDocBytes(doc: StoredDoc): Promise<Buffer | null> {
  try {
    return await readFile(/*turbopackIgnore: true*/ blobPath(doc));
  } catch {
    return null;
  }
}

/**
 * Store one uploaded file. Returns null if it is empty or over the size
 * cap — the caller turns that into a per-file error so one bad file in a
 * multi-file drop doesn't fail the rest.
 */
export async function saveDoc(ownerId: string, file: File): Promise<StoredDoc | null> {
  if (file.size === 0 || file.size > MAX_UPLOAD_BYTES) return null;

  const bytes = Buffer.from(await file.arrayBuffer());
  // Trust the bytes we actually read, not the reported size.
  if (bytes.byteLength === 0 || bytes.byteLength > MAX_UPLOAD_BYTES) return null;

  const ext = safeExt(file.name);
  const doc: StoredDoc = {
    id: randomUUID(),
    ownerId,
    name: safeName(file.name),
    ext,
    size: bytes.byteLength,
    kind: kindForExt(ext),
    uploadedAt: new Date().toISOString(),
  };

  await ensureDir(ownerId);
  await writeFile(/*turbopackIgnore: true*/ blobPath(doc), bytes);
  // Metadata last: a crash between the two leaves an orphan blob, which
  // `listDocs` ignores, rather than a record pointing at nothing.
  await writeFile(
    /*turbopackIgnore: true*/ metaPath(ownerId, doc.id),
    JSON.stringify(doc, null, 2),
    "utf-8",
  );

  return doc;
}

export async function deleteDoc(ownerId: string, id: string): Promise<boolean> {
  const doc = await getDoc(ownerId, id);
  if (!doc) return false;
  await rm(/*turbopackIgnore: true*/ metaPath(ownerId, id), { force: true });
  await rm(/*turbopackIgnore: true*/ blobPath(doc), { force: true });
  return true;
}
